on: [push]

jobs:
  run_unit_test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt install -y gcc g++ cmake
          python -m pip install --upgrade pip
          python -m pip install ninja pybind11 torch

      - name: Build xgrammar and run C++ tests
        run: |
          echo "set(XGRAMMAR_BUILD_CXX_TESTS ON)" >> cmake/config.cmake
          mkdir build && cd build
          cmake .. -G Ninja
          ninja && ctest
          cd ..

      - name: Run Python tests
        run: |
          pip install -e .
          pytest -m "not hf_token_required"
