on: [push]

jobs:
  run_unit_test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build xgrammar from source
        run: |
          echo "set(XGRAMMAR_BUILD_CXX_TESTS ON)" >> cmake/config.cmake
          pip install -e .

      - name: Run C++ tests
        run: |
          cd build && ctest && cd ..

      - name: Run Python tests
        run: |
          pip install pytest
          pytest -m "not hf_token_required"
